import type { Metadata } from "next";
import "./globals.css";
import HeaderLayout from "@/components/layout/HeaderLayout";

export const metadata: Metadata = {
  title: "Red Velvet",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="bg-black">
      <body className=" min-w-[600px] mx-auto">
        <HeaderLayout />
        {children}
      </body>
    </html>
  );
}
